templates/ecoquartiers.recoconseil.fr/account/email/email_confirmation_signup_message.html
templates/ecoquartiers.recoconseil.fr/account/email/email_confirmation_subject.txt
templates/ecoquartiers.recoconseil.fr/account/email/password_reset_key_message.html
templates/ecoquartiers.recoconseil.fr/account/email/password_reset_key_subject.txt
templates/ecoquartiers.recoconseil.fr/magicauth/email.html
templates/ecoquartiers.recoconseil.fr/magicauth/email.txt
templates/ecoquartiers.recoconseil.fr/magicauth/email_subject.txt
templates/urbanvitaliz.fr/account/email/email_confirmation_signup_message.html
templates/urbanvitaliz.fr/account/email/email_confirmation_subject.txt
templates/urbanvitaliz.fr/account/email/password_reset_key_message.html
templates/urbanvitaliz.fr/account/email/password_reset_key_subject.txt
templates/urbanvitaliz.fr/magicauth/email.html
templates/urbanvitaliz.fr/magicauth/email.txt
templates/urbanvitaliz.fr/magicauth/email_subject.txt

Email surcharge for Ecoquartiers

[Email][Templates] Ecoquartiers version

---

templates/ecoquartiers.recoconseil.fr/header/menu-top-logo.html
templates/ecoquartiers.recoconseil.fr/header/menu-top.html
templates/sosponts.recoconseil.fr/header/menu-top-logo.html
templates/sosponts.recoconseil.fr/header/menu-top.html

Nouvelle version du header pour écoquartiers & sosponts

[Header] Logged / unlogged version

---

templates/urbanvitaliz.fr/footer.html

Typo fix footer   Conditions d'utilisons > Conditions d'utilisation

[UV] fix mispelled footer

---

templates/sosponts.recoconseil.fr/footer.html
templates/sosponts.recoconseil.fr/home/statistics.html

[Trello Ticket](https://trello.com/c/ZkK1Krp9/1867-peaufiner-la-page-stats-sosp)

[SOSPONTS] fix typo, align grid item + add footer link

---

templates/bacasable.recoconseil.fr/header/menu-top-logo.html
templates/bacasable.recoconseil.fr/home/home.html

Remplacement Recoco -> Recommendations Collaboratives

[Bacasable] Update menu-top-logo and home.html templates

---

templates/bacasable.recoconseil.fr/home/home.html

[Trello ticket](https://trello.com/c/RJh0tdnf/1937-sur-le-site-bac-%C3%A0-sable-ajouter-les-logos-du-mte-et-de-lanct-comme-sur-uv)

[BACASABLE] Add MTE and ANCT logo

---

templates/bacasable.recoconseil.fr/header/menu-top.html
templates/ecoquartiers.recoconseil.fr/header/menu-top.html
templates/monespacecollectivite.incubateur.anct.gouv.fr/header/menu-top.html
templates/sos-mobilites-hdf.recoconseil.fr/header/menu-top.html
templates/sosponts.recoconseil.fr/home/statistics.html

- Page stats fix text color
- Fix header

[SOSPONTS] fix page stats

---

static/ecoquartiers.recoconseil.fr/home/css/statistics/statistics-ecoquartiers.scss
templates/ecoquartiers.recoconseil.fr/footer.html
templates/ecoquartiers.recoconseil.fr/home/statistics.html

Ce commit est lié à la pull request #302 "[EQ] fix - add variable resources non draft".
Ajout de la page statistiques pour ecoquartiers. Le commit 302 ajoute une variable affichant le nombre de ressources liées au projet ecoquartiers.

[EQ] feat - add statistics page for EQ

---

templates/accompagnement.encommuns.org/home/home.html
templates/urbanvitaliz.fr/header/menu-top-secondary.html

Correctif du bug de la release !
Modification url prefill.

[Fix] changement url

---

templates/accompagnement.encommuns.org/home/home.html

[EnCommuns] fix - add modal onboarding page home

---

templates/accompagnement.encommuns.org/header/menu-top-logo.html

[EnCommuns] style - add css to logo EnCommuns

---

templates/accompagnement.encommuns.org/home/home.html

Changement du nom du bouton principal

[EnCommuns] fix - change button name

---

templates/accompagnement.encommuns.org/header/menu-top.html
templates/ecoquartiers.recoconseil.fr/header/menu-top-secondary.html
templates/ecoquartiers.recoconseil.fr/header/menu-top.html
templates/monespacecollectivite.incubateur.anct.gouv.fr/header/menu-top.html
templates/sos-mobilites-hdf.recoconseil.fr/header/menu-top.html
templates/sosponts.recoconseil.fr/header/menu-top.html
templates/urbanvitaliz.fr/header/menu-top-secondary.html

Modification des surcharges de chaque pf pour mettre le menu secondaire ("méthodologie" pour UV et "ressources" pour toutes) au niveau du premier header.

[fix] merge secondary menu with the first one for all pf

---

templates/accompagnement.encommuns.org/header/menu-top.html
templates/bacasable.recoconseil.fr/header/menu-top-secondary.html
templates/bacasable.recoconseil.fr/header/menu-top.html
templates/ecoquartiers.recoconseil.fr/header/menu-top-secondary.html
templates/ecoquartiers.recoconseil.fr/header/menu-top.html
templates/monespacecollectivite.incubateur.anct.gouv.fr/header/menu-top.html
templates/sos-mobilites-hdf.recoconseil.fr/header/menu-top.html
templates/sosponts.recoconseil.fr/header/menu-top.html
templates/urbanvitaliz.fr/header/menu-top-secondary.html

Correctif bug affichage menu des éléments ressources et méthodologie tout en refactorisant le css.
Cette PR est liée à la PR du même nom et à venir sous peu sur le repo' recommandation collaborative.

[Hotfix] refacto css and fix menu vertical alignment

---

templates/sosponts.recoconseil.fr/home/home.html
templates/urbanvitaliz.fr/home/home.html

Ajout d'une classe au texte de la bannière custom de SosPonts et UV pour corriger l'alignement avec du margin.

[UV][SOSPONTS] fix - update class from custom banner

---

templates/depannemarenov.beta.gouv.fr/home/home.html

Modification du titre du portail Dépanne ma Rénov'

[DMR] feat - change dmr title

---

templates/accompagnement.encommuns.org/header/menu-top-logo.html
templates/bacasable.recoconseil.fr/header/menu-top.html
templates/depannemarenov.beta.gouv.fr/header/menu-top-logo.html
templates/ecoquartiers.recoconseil.fr/header/menu-top-logo.html
templates/ecoquartiers.recoconseil.fr/header/menu-top-secondary.html
templates/ecoquartiers.recoconseil.fr/header/menu-top.html

Modification de la taille du logo d'écoquartiers. 
Modification de la taille et du padding des logos d'EnCommuns et DépanneMaRénov'.

[EnCommuns][DMR][ecoQ] change logo size and padding when connected

---

templates/bacasable.recoconseil.fr/header/menu-top-secondary.html
templates/ecoquartiers.recoconseil.fr/header/menu-top-secondary.html
templates/urbanvitaliz.fr/header/menu-top-secondary.html

Ajout du lien vers la page modération des projets

Feat/refonte moderation project#494

---

templates/urbanvitaliz.fr/footer.html

Ajout d'un bouton budget dans le footer qui mène vers la page du même nom.

[UV] feat - add budget on footer

---

templates/depannemarenov.beta.gouv.fr/home/home.html

Changement du texte de la page d'accueil du portail dépanne ma rénov'.

[DMR] feat - update text from homepage

---

templates/depannemarenov.beta.gouv.fr/footer.html

correction de l'url de la plaquette du footer de dmr

[DMR] fix url plaquette in footer

---

templates/urbanvitaliz.fr/header/menu-top-secondary-left.html

Modification de la classe du bouton Méthodologie du menu pour changer 2 classes d'espacement bootstrap par 2 classes du dsfr

[UV] update class from bootstrap to dsfr for methodo button

---

templates/monespacecollectivite.incubateur.anct.gouv.fr/home/home.html

Changement du wording de la page d'accueil de mon espace collectivité.

[MEC] change home wording

---

templates/urbanvitaliz.fr/footer.html

Changement url de la page politique de confidentialité avec celle du cms wagtail.

[fix] update privacy policy link to use slugurl template tag

---

templates/protect-envi.beta.gouv.fr/home/home.html
templates/urbanvitaliz.fr/home/regional_actors.html

Ajout d'un bouton pour déposer un projet pour le portail Protect-Envi.

Ajout bouton projet Protect Envi

---

templates/sosponts.recoconseil.fr/home/home.html

réduction de la taille du second bouton secondaire du héro du portail SOS Ponts

[fix] Correction de l'affichage du 2ème bouton secondaire du héro 

---

static/urbanvitaliz.fr/home/css/home/home-urbanvitaliz.scss

Suppression des marges droite et gauche de la page d'accueil d'UV

[fix] suppression des marges UV

---

templates/sos-mobilites-hdf.recoconseil.fr/home/home.html

Modification du texte descriptif du portail sos mobilité pour retirer l'effet italic.

[fix] Modification texte italic sos mobilité

---

templates/sosponts.recoconseil.fr/footer.html

Correction de l'url du lien vers la page qui sommes nous du pied de page du portail SOS Ponts

[SOSP] Correction url pied de page 

---

templates/sosponts.recoconseil.fr/footer.html

Resolve https://github.com/betagouv/recommandations-collaboratives/issues/1098

[SOSPONTS] Mise à jour du lien de la page qui sommes nous dans le footer

---

templates/urbanvitaliz.fr/home/home.html

Changement du texte du bouton secondaire sur le héro du portail UV pour mener vers un mail.

fix: changement nom bouton secondaire UV

---

templates/sosponts.recoconseil.fr/footer.html

Importation des tags wagtails.

[SOSP] importation wagtailcore tags

---

static/depannemarenov.beta.gouv.fr/home/css/home/home-depannemarenov.scss
static/mission-adaptation.fr/home/css/home/home-mission-adaptation.scss
static/protect-envi.beta.gouv.fr/home/css/home/home-protect-envi.scss
templates/accompagnement.encommuns.org/home/home.html
templates/bacasable.recoconseil.fr/home/home.html
templates/corspad.recoconseil.fr/home/home.html
templates/depannemarenov.beta.gouv.fr/home/home.html
templates/ecoquartiers.recoconseil.fr/home/home.html
templates/mission-adaptation.fr/home/home.html
templates/monespacecollectivite.incubateur.anct.gouv.fr/home/home.html
templates/protect-envi.beta.gouv.fr/home/home.html
templates/sos-mobilites-hdf.recoconseil.fr/home/home.html
templates/sosponts.recoconseil.fr/home/home.html
templates/urbanvitaliz.fr/home/home.html

Création de classe avec la méthode bem pour rendre le nouveau héro responsive.
Cette PR est liée avec celle de recoco : https://github.com/betagouv/recommandations-collaboratives/pull/1127

Fix responsive pour le nouveau héro des portails

---

templates/accompagnement.tiers-lieux.org/home/home.html

Correction orthographique de la page d'accueil du portail Tiers Lieux

Correction orthographique TL

---

templates/urbanvitaliz.fr/footer.html

[UV] Correction de la mention en double de budget dans le footer

---

templates/pui-asu.recoconseil.fr/home/home.html

Ajout d'un point sur la page d'accueil du portail  de la Sorbonne.

[PUI] ajout d'un point sur la page d'accueil

---

templates/sosponts.recoconseil.fr/home/home.html

Changement du texte du bouton principal

[SOSP] Changement du texte du bouton principal

---

templates/mission-adaptation.fr/home/home.html
templates/sosponts.recoconseil.fr/account/fragments/button_pending_advisor_request.html
templates/sosponts.recoconseil.fr/home/home.html
templates/urbanvitaliz.fr/account/fragments/button_pending_advisor_request.html
templates/urbanvitaliz.fr/home/home.html
templates/urbanvitaliz.fr/home/regional_actors.html

- Ajout d'un bouton sur la home
- Mise à jour du lien sur la page acteurs locaux
- Ajout des boutons de téléchargement de doc conseiller + lien Guide conseiller
- Ajout d'un bouton sur la home
- Ajout d'un bouton de téléchargement de doc conseiller
- Ajout d'un bouton sur la home

[feat] Demande de compte conseiller

---

static/mission-adaptation.fr/home/css/statistics/statistics-mission-adaptation.scss
templates/mission-adaptation.fr/home/statistics.html

Ajout page statistique au portail Mission-Adaptation.
Resolve #147

Ajout page statistique au portail Mission-Adaptation

---

templates/sosponts.recoconseil.fr/home/privacy.html

Suppression des occurences de posthog.
Cette PR est liée avec [cette PR de recommandations-collaboratives](https://github.com/betagouv/recommandations-collaboratives/pull/1351).

Suppression de posthog

---

templates/urbanvitaliz.fr/home/contact.html

Suppression du numéro de téléphoen de la page de contact du portail UV.

Suppression du téléphone sur UV
